// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe4m6e4jKzzwZPWZmv-0mejbZJJ9uiqEA',
    appId: '1:941302754836:web:78db70d9db7c48a1534101',
    messagingSenderId: '941302754836',
    projectId: 'meditrack-a1ef2',
    authDomain: 'meditrack-a1ef2.firebaseapp.com',
    storageBucket: 'meditrack-a1ef2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYx_gGt7BWKyWCvONrIrbBVRtZbFZN4q4',
    appId: '1:941302754836:android:1221d1b686a67239534101',
    messagingSenderId: '941302754836',
    projectId: 'meditrack-a1ef2',
    storageBucket: 'meditrack-a1ef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBE2fOvCA5c3dSqGNiIoIdyPluM8To04c',
    appId: '1:941302754836:ios:0de335e502f061c0534101',
    messagingSenderId: '941302754836',
    projectId: 'meditrack-a1ef2',
    storageBucket: 'meditrack-a1ef2.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBE2fOvCA5c3dSqGNiIoIdyPluM8To04c',
    appId: '1:941302754836:ios:0de335e502f061c0534101',
    messagingSenderId: '941302754836',
    projectId: 'meditrack-a1ef2',
    storageBucket: 'meditrack-a1ef2.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );
}
